export const FETCH_SUCCESS = 'FETCH_SUCCESS'
export const FETCH_FAIL = 'FETCH_FAIL'
export const MSG_SUCCESS = 'MSG_SUCCESS'
export const MSG_FAIL = 'MSG_FAIL'
export const ADD_ALERT = 'ADD_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'
export const PLANS_LOADING = 'PLANS_LOADING'
export const CONTACT_LOADING = 'CONTACT_LOADING'